FROM node:18

# Copie uniquement package.json
COPY package.json package-lock.json ./

# Installation propre de tous les modules
RUN rm -rf node_modules && npm install && npm rebuild bcrypt --build-from-source

# Copie le reste des fichiers
COPY . .

EXPOSE 3003

CMD ["node", "server_restaurant.js"]