version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: accountdb
    ports:
      - "5433:5432"  # Externe:Interne
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  account-service:
    build:
      context: ./services/account/serveur_node
    container_name: account_service
    ports:
      - "8080:3000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork
    volumes:
      - ./services/account/serveur_node:/app
      - /app/node_modules

  api-gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8081:8081"
    depends_on:
      - account-service
    networks:
      - mynetwork
    volumes:
      - ./api_gateway:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork
    depends_on:
      - api-gateway

  mobile-livreur:
    build:
      context: ./mobile/livreur
    container_name: mobile_livreur
    ports:
      - "3001:3000"  # Accessible via localhost:3001
    volumes:
      - ./mobile/livreur:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork
    depends_on:
      - api-gateway

volumes:
  pgdata:

networks:
  mynetwork:
    driver: bridge
