# Utilise une image Node.js officielle
FROM node:18

# Définit le dossier de travail dans le conteneur
WORKDIR /app

# Copie les fichiers du projet
COPY package.json package-lock.json ./
RUN npm install

# Copie le reste des fichiers
COPY . .

# Expose le port utilisé par l'application
EXPOSE 8081

# Commande pour démarrer l'application
CMD ["node", "api.js"]
