services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork  # Utilisation du même réseau partagé

networks:
  mynetwork:
    external: true  # Indique qu'on utilise un réseau existant

volumes:
  pgdata: