FROM node:18

WORKDIR /app

# Copie uniquement package.json
COPY package.json ./

# Installation propre de tous les modules
RUN rm -rf node_modules && npm install && npm rebuild bcrypt --build-from-source

# Copie le reste des fichiers
COPY . .

EXPOSE 3000

CMD ["node", "server.js"]
